### ISSUE TITLE
Possibility of SQL-injection

### ISSUE THREAD

**Issue by amatiushkin** [samiur98/Navy-Notes#3]
There are many places in the code, which follows this pattern:

https://github.com/samiur98/Navy-Notes/blob/be2a70e55b438e068d576fa9a6020a3234a020be/server/routes/users.js#L37-L38

If I read it right, it takes user input and injects it right into SQL request without validation and verification, which is a first out of [top-10](https://owasp.org/www-project-top-ten/) security vulnerabilities of web app. 

Prepared statement or any over form of escaping would do the trick (pointer to [documentation](https://github.com/mysqljs/mysql#escaping-query-values)).

**Comment by samiur98** [comment]
Escaping is performed, that code prepares the SQL statement that is carried out by another function. Escaping is performed in that function.

**Comment by amatiushkin** [comment]
@samiur98 Which function performs escaping in your opinion? 
As far as I see SQL statement unmodified to [mysql](https://github.com/mysqljs/mysql) lib, where it is assigned to [Query](https://github.com/mysqljs/mysql/blob/master/lib/protocol/sequences/Query.js#L12) instance, which is supposed to send it over to database server.
